name = "Testmodpack"
author = "Bety"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a0087a55af9542d217bb9958e8685b44cecc0362ef89ac4accc7989c375a373"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
